config/routes.rb
Blog::Application.routes.draw do
  devise_for :users

  resources :groups, only: [:index]

  resources :users, only: [:show] do
    resources :posts, only: [:index, :show] do
      resources :items, only: [:show]
    end
  end

  resources :imports, only: [:index] do
    collection do
      get :box
    end
  end

  root 'welcome#index'

  

end

app/models/item.rb
class Item < ActiveRecord::Base

  serialize :exifs

  belongs_to :user
  has_and_belongs_to_many :posts

  mount_uploader :file, ItemUploader

  after_create :create_posts
  before_save :extract_exif

  validates_uniqueness_of :path, allow_nil: false, scope: :user
  validates :user, presence: true

  def create_posts
    current_path = Pathname.new self.path
    post = Post.find_or_create_by!(path: current_path.parent.to_s, user: user)
    if post.started_at.nil? or ( started_at and post.started_at > started_at )
      post.started_at = started_at
    end

    if post.ended_at.nil? or (ended_at and post.ended_at < ended_at)
      post.ended_at = ended_at
    end

    post.items << self
    post.save!
  end

  def exifs= exifs
    self[:exifs] = exifs
    if exifs['Rating']
      self.rating= exifs['Rating']
    end
    if exifs['DateTimeOriginal']
      self.started_at= exifs['DateTimeOriginal']
      self.ended_at= exifs['DateTimeOriginal']
    end
  end

  def extract_exif
    exifs = MiniExiftool.new file.current_path
    self.exifs= exifs.to_hash
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :require_user
  before_filter :require_post
  before_filter :require_item
  before_filter :check_access

  def show
    expires_in 5.minutes, :public => true
    @next = @post.next(@item)
    @previous = @post.previous(@item)
    render layout: 'application_without_nav'
  end
  private

    def require_item
      @item = @post.items.find(params[:id])
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_item.html.haml
= link_to user_post_item_path(user_id: @user.id, post_id: post.id, id: item.id) do
  = image_tag item.file.url(:thumb), title: item.rating, class: 'item-image', title: item.path

app/views/items/show.html.haml
.fullscreen
  .viewer
    .content
      = image_tag @item.file.url, title: @item.path
    - if @next
      =link_to user_post_item_path( post_id: @post, id: @next, user_id: @user), rel: 'prefetch', class: 'control next preload' do
        %p
    - if @previous
      =link_to user_post_item_path( post_id: @post, id: @previous, user_id: @user), class: 'control previous preload' do
        %p
    .control.fullscreen_toggle
    =link_to user_post_path( id: @post, user_id: @user), class: 'control home' do
      %p
-#
  .row
    .col-xs-10
      = @item.path
      %table
        %thead
          %tr
            %td key
            %td value
        %tbody
          - @item.exifs.each do |exif|
            %tr
              %td= exif[0]
              %td= exif[1]
  - content_for :nav do
    =link_to 'Go back', user_post_path(id: @post, user_id: @user), class: 'btn btn-primary'