config/routes.rb
Blog::Application.routes.draw do
  devise_for :users

  resources :groups, only: [:index]

  resources :users, only: [:show] do
    resources :posts, only: [:index, :show] do
      resources :items, only: [:show]
    end
  end

  resources :imports, only: [:index] do
    collection do
      get :box
    end
  end

  root 'welcome#index'

  

end

app/models/post.rb
class Post < ActiveRecord::Base

  validates_uniqueness_of :path, allow_nil: false, scope: :user_id

  has_and_belongs_to_many :items
  belongs_to :user

  validates :user, presence: true

  def path= path
    self[:path] = path
    if self.name.blank?
      path_name = Pathname.new path
      self.name= self.class.postname(path_name.basename.to_s)
    end
  end

  def next(item)
    list = ordered_items.to_a
    list[ list.index(item) + 1 ]
  end

  def ordered_items
    items.order(:started_at)
  end

  def previous(item)
    list = ordered_items.to_a
    index = list.index(item) - 1
    index < 0 ? nil : list[index]
  end

  class << self
    def postname(filename)
      if filename.match /(.*\/)*\d{4}[-_]+\d\d[-_]+\d\d[-_]+(.*)/
        return $2.humanize.squish
      end
      filename
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :require_user
  before_filter :check_access

  def index
    @posts = @user.posts.order(started_at: :desc)
  end

  def show
    @post = @user.posts.find(params[:id])
    respond_to do |format|
      format.html
      format.js
    end
  end

end

app/views/posts/_no_post.html.haml
You don't have any posts yet.
= link_to "Import my first posts", imports_path, class: 'btn btn-primary'

app/views/posts/_post.html.haml
- items = post.items.order('rating DESC').limit(3)
.row{id: "post-#{post.id}"}
  .col-xs-12
  .row
    .col-xs-12
      %h1= link_to post.name, user_post_path(user_id: @user, id: post)
  .row
    .col-xs-12
      =render items, post: post

app/views/posts/_show.html.haml
.row{id: "post-#{@post.id}"}
%h1= @post.name
= render @post.items.order('started_at'), post: @post

app/views/posts/index.html.haml
= render(@posts) || render(partial: 'no_post')

app/views/posts/show.html.haml
= render 'show'