config/routes.rb
Blog::Application.routes.draw do
  devise_for :users

  resources :groups, only: [:index]

  resources :users, only: [:show] do
    resources :posts, only: [:index, :show] do
      resources :items, only: [:show]
    end
  end

  resources :imports, only: [:index] do
    collection do
      get :box
    end
  end

  root 'welcome#index'

  

end

app/views/layouts/_application_without_nav.html.haml
!!!
%html
  %head
    %title Blog
    %meta{name: 'viewport', content: 'user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0'}
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    = yield
    /
      Delayed Jobs : #{Delayed::Job.count}

    %script{"data-turbolinks-eval" => "false"}
      var analytics=analytics||[];(function(){var e=["identify","track","trackLink","trackForm","trackClick","trackSubmit","page","pageview","ab","alias","ready","group"],t=function(e){return function(){analytics.push([e].concat(Array.prototype.slice.call(arguments,0)))}};for(var n=0;n<e.length;n++)analytics[e[n]]=t(e[n])})(),analytics.load=function(e){var t=document.createElement("script");t.type="text/javascript",t.async=!0,t.src=("https:"===document.location.protocol?"https://":"http://")+"d2dq2ahtl5zl1z.cloudfront.net/analytics.js/v1/"+e+"/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(t,n)};analytics.load("#{ENV['SEGMENT_IO_JS']}");

app/views/layouts/_nav.html.haml
.row
  .col-cs-12
    = link_to 'Home', root_path, class: 'btn'
    -if user_signed_in?
      = link_to "Manage my account", edit_user_registration_path, class: 'btn btn-primary'
      = link_to 'log out', destroy_user_session_path, class: 'btn btn-primary'
      = link_to t('.import'), imports_path, class: 'btn btn-primary'
      = link_to "See my posts", user_posts_path(user_id: current_user), class: 'btn btn-primary'
    -else
      = link_to 'log in', new_user_session_path, class: 'btn btn-primary'
      = link_to 'register', new_user_registration_path, class: 'btn btn-primary'
    =yield :nav
-#%nav.navbar.navbar-default.navbar-fixed-top{role: 'navigation'}
  %ul.nav.navbar-nav
  %p.navbar-text= "asdasdasdasd"
  -#%ul.nav.navbar-nav.navbar-right

app/views/layouts/application.html.haml
= render layout: 'layouts/application_without_nav' do
  .container
    = render 'layouts/nav'
    - flash.each do |name, msg|
      %div{class: "alert alert-#{name}"}
        =msg
    = yield

app/views/layouts/application_without_nav.html.haml
= render layout: 'layouts/application_without_nav' do
  = yield